name: SCANPLOT
channels:
  - defaults
  - conda-forge
dependencies:
  - cartopy=0.25.0
  - geopandas=1.1.1
  - geoviews=1.14.1
  - holoviews=1.22.0
  - hvplot=0.12.1
  - jupyterlab=4.5.0
  - matplotlib=3.10.7
  - numpy=2.3.5
  - pandas=2.3.3
  - pip=25.3
  - python=3.13.11
  - scipy=1.16.3
  - seaborn=0.13.2
  - xarray=2025.10.1
  - pip:
      - skillmetrics==1.2.4
      - xlsxwriter==3.2.9
prefix: /home/carlos/miniconda3/envs/SCANPLOT
